// Copyright © Unbroken AB
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#pragma once

#include <Mib/Core/Core>
#include <Mib/Concurrency/ConcurrencyManager>
#include <Mib/Concurrency/DistributedApp>
#include <Mib/Process/ProcessLaunchActor>

namespace NMib::NConcurrency
{
	struct CDistributedAppInterfaceLaunchActor : public NProcess::CProcessLaunchActor
	{
		using FOnUseTicket = TCActorFunctor
			<
				TCFuture<void>
				(
					NStr::CStr _HostID
					, CCallingHostInfo _HostInfo
					, NContainer::CByteVector _CertificateRequest
				)
			>
		;
		using FRequestTicket = TCActorFunctor<TCFuture<NStr::CStr> ()>;

		CDistributedAppInterfaceLaunchActor
			(
				NWeb::NHTTP::CURL const &_Address
				, TCActor<CDistributedActorTrustManager> const &_TrustManager
				, FOnUseTicket &&_fOnUseTicket
				, TCActorFunctor<TCFuture<void> (NStr::CStr _Error)> &&_fOnLaunchError
				, NStr::CStr const &_Description
				, NStr::CStr const &_LaunchID
				, bool _bDelegateTrust
				, NStr::CStr const &_RequestTicketMagic = {} /// Fixed request ticket magic for relaunching environments with a frozen process environment; empty generates a random one
			)
		;

		/// Launch on behalf of a manager on another host: tickets are generated by
		/// that manager through the request functor instead of a local trust manager
		CDistributedAppInterfaceLaunchActor
			(
				NWeb::NHTTP::CURL const &_Address
				, FRequestTicket &&_fRequestTicket
				, TCActorFunctor<TCFuture<void> (NStr::CStr _Error)> &&_fOnLaunchError
				, NStr::CStr const &_Description
				, NStr::CStr const &_LaunchID
			)
		;
		~CDistributedAppInterfaceLaunchActor();

	private:
		bool fp_WillFilterOutput() override;
		void fp_FilterOutput(NProcess::EProcessLaunchOutputType _OutputType, NStr::CStr &o_Output) override;
		void fp_ModifyLaunch(CLaunch &o_Launch) override;

		void fp_HandleTicketRequest();

		struct CHandleRequest
		{
			CActorSubscription m_NotificationsSubscription;
		};

		TCActor<CDistributedActorTrustManager> mp_TrustManager;
		NWeb::NHTTP::CURL mp_Address;
		NStr::CStrSecure mp_RequestTicketMagic;
		NStr::CStr mp_Description;
		NStr::CStr mp_LaunchID;
		FOnUseTicket mp_fOnUseTicket;
		FRequestTicket mp_fRequestTicket;
		TCActorFunctor<TCFuture<void> (NStr::CStr _Error)> mp_fOnLaunchError;
		NContainer::TCMap<NStr::CStr, CHandleRequest> mp_HandleRequests;
		bool mp_bDelegateTrust = false;
	};
}
