// Copyright © 2015 Hansoft AB
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include <Mib/Core/Core>
#include <Mib/Encoding/JSONShortcuts>

#include "Malterlib_Concurrency_DistributedApp.h"
#include "Malterlib_Concurrency_DistributedApp_CommandLine_SpecificationInternal.h"

namespace NMib
{
	using namespace NStr;
	using namespace NFile;
	using namespace NPtr;
	using namespace NEncoding;
	using namespace NContainer;
	
	namespace NConcurrency
	{
		CDistributedAppCommandLineResults::COutput::COutput() = default;
		
		CDistributedAppCommandLineResults::COutput::COutput(NStr::CStr const &_Output, EOutputType _OutputType)
			: m_OutputType(_OutputType)
			, m_Output(_Output)
		{
		}

		CDistributedAppCommandLineResults::CDistributedAppCommandLineResults() = default;
		
		CDistributedAppCommandLineResults::CDistributedAppCommandLineResults(NStr::CStr const &_Output, EOutputType _OutputType)
		{
			m_Output.f_Insert(fg_Construct(_Output, _OutputType));
		}																			 

		void CDistributedAppCommandLineResults::f_AddStdOut(CStr const &_Output)
		{
			m_Output.f_Insert(fg_Construct(_Output, EOutputType_StdOut));
		}
		
		void CDistributedAppCommandLineResults::f_AddStdErr(CStr const &_Output)
		{
			m_Output.f_Insert(fg_Construct(_Output, EOutputType_StdErr));
		}
		
		void CDistributedAppCommandLineResults::f_SetExitStatus(uint32 _Status)
		{
			m_Status = _Status;
		}
		
		TCContinuation<CDistributedAppCommandLineResults> CDistributedAppActor::f_RunCommandLine
			(
				NStr::CStr const &_FromHostID
				, NStr::CStr const &_Command
				, NEncoding::CEJSON const &_Params
			)
		{
			if (!fp_HasCommandLineAccess(_FromHostID))
				return DMibErrorInstance("Access denied");
			
			auto &SpecInternal = *(mp_pCommandLineSpec->mp_pInternal);
			
			auto *pCommand = SpecInternal.m_CommandByName.f_FindEqual(_Command);
			
			if (!pCommand)
				return DMibErrorInstance("Non-existant command line command");

			auto &Command = **pCommand;
			if (!Command.m_fActorRunCommand)
				return DMibErrorInstance("Non-actor cammand");

			try
			{
				return Command.m_fActorRunCommand(SpecInternal.f_ValidateParams(Command, _Params));
			}
			catch (NException::CException const &_Exception)
			{
				return _Exception;
			}
		}
		
		TCContinuation<CDistributedAppCommandLineResults> CDistributedAppActor::f_CommandLine_AddConnection(NStr::CStr const &_Ticket)
		{
			CDistributedActorTrustManager::CTrustTicket Ticket;
			try
			{
				Ticket = CDistributedActorTrustManager::CTrustTicket::fs_FromStringTicket(_Ticket);
			}
			catch (NException::CException const &_Exception)
			{
				return DMibErrorInstance(fg_Format("Faild to decode ticket: {}", _Exception.f_GetErrorStr()));
			}
			
			TCContinuation<CDistributedAppCommandLineResults> Continuation;
			mp_State.m_TrustManager(&CDistributedActorTrustManager::f_AddClientConnection, Ticket, 30.0) 
				> Continuation / [Continuation](CStr &&_HostID)
				{
					DMibLogWithCategory(Mib/Concurrency/App, Info, "Add connection to host '{}'", _HostID);
					Continuation.f_SetResult(_HostID + DMibNewLine);
				}
			;
			return Continuation;
		}
		
		TCContinuation<CDistributedAppCommandLineResults> CDistributedAppActor::f_CommandLine_GenerateTrustTicket(CStr const &_ForListen)
		{
			CDistributedActorTrustManager_Address ForListen;
			if (_ForListen.f_IsEmpty())
			{
				if (!mp_PrimaryListen.m_URL.f_IsValid())
					return DMibErrorInstance("The app has not been configured to listen, so ticket cannot be generated");
				ForListen = mp_PrimaryListen;
			}
			else
				ForListen.m_URL = _ForListen;
				
			TCContinuation<CDistributedAppCommandLineResults> Continuation;
			mp_State.m_TrustManager(&CDistributedActorTrustManager::f_GenerateConnectionTicket, mp_PrimaryListen) 
				> Continuation / [Continuation](CDistributedActorTrustManager::CTrustTicket &&_Ticket)
				{
					DMibLogWithCategory(Mib/Concurrency/App, Info, "Generated trust ticket with address: {}", _Ticket.m_ServerAddress.m_URL.f_Encode());
					Continuation.f_SetResult(_Ticket.f_ToStringTicket() + DMibNewLine);
				}
			;
			return Continuation;
		}
		
		void CDistributedAppActor::fp_BuildCommandLine(CDistributedAppCommandLineSpecification &o_CommandLine)
		{
			{
				auto Distributed = o_CommandLine.f_AddSection("Distributed Computing", "These commands are used to manage connectability and trust between different hosts.");
				Distributed.f_RegisterCommand
					(
						{
							"Names"_= {"--add-connection"}
							, "Description"_= "Add a connection to a remote distributed actor host.\n"
								"The ticket encodes the url of the remote host and can usually be generated by the remote host by running --generate-connection-ticket.\n"
								"A ticket can only be used once and expires after a set time.\n"
							, "Output"_= "The host ID of the remote server."
							, "Parameters"_=
							{
								"Ticket"_= 
								{
									"Default"_= ""
									, "Description"_= "Specify ticket to use for adding the connection"
								}
							}
						}
						, [this](CEJSON const &_Params)
						{
							return f_CommandLine_AddConnection(_Params["Ticket"].f_String());
						}
					)
				;

				Distributed.f_RegisterCommand
					(
						{
							"Names"_= {"--generate-connection-ticket"}
							, "Description"_= "Generate a ticket that can be used to connect to a remote host.\n"
								" The ticket encodes the url of this host."
								" A ticket can only be used once and expires after a set time."
							, "Output"_= "The host ID of the remote server."
							, "Parameters"_=
							{
								"ForListenURL?"_= 
								{
									"Default"_= ""
									, "Description"_=  "Specify the URL you want to generate a ticket for.\n"
										"This is needed because the ticket includes the public certificate to connect to this server. Every host has a different certificate" 
										" so you need to specify the listen address to be able to know which certificate to send with the ticket.\n"
										"If you do not specify the URL the primary listen URL will be used. The primary listen URL is the first listen URL specified in the config file."
								}
							}
						}
						, [this](CEJSON const &_Params)
						{
							return f_CommandLine_GenerateTrustTicket(_Params["ForListenURL"].f_String());
						}
					)
				;
			}
		}
	}		
}
